### PR TITLE
fix deprecation warning

### PR DESCRIPTION
**Pull request by davidsteinberger**

### CODE REVIEW

**Comment by kiwiupover** [comment]
Thanks @davidsteinberger.
It looks like the tests are failing. We will need to look into that.

**Comment by davidsteinberger** [comment]
Sorry, my bad, haven't run the tests. I hope I can look into that tomorrow. The container param is definitely deprecated: http://emberjs.com/deprecations/v2.x/

**Comment by davidsteinberger** [comment]
I've updated the PR and Travis passes now. Is AppVeyor broken?

**Comment by davidsteinberger** [comment]
Any problem with this PR?

**Comment by kiwiupover** [comment]
Can we add 1.13 to ember try then we should be good to go

**Comment by davidsteinberger** [comment]
Sorry for the late response. #23 silences the deprecation warning. This PR upgrades to the latest ember-cli and deps and adds test-coverage for ember-1.13.11.

**Comment by kiwiupover** [comment]
thanks heaps mate.

**Pull request merged**
