### PR TITLE
Switch to ember-auto-import and Babel 7

### PR DESCRIPTION
**Pull request by wagenet**

### CODE REVIEW

**Comment by kiwiupover** [comment]
WAHOO!!

**Comment by wagenet** [comment]
@kiwiupover I hate to say this, but have you successfully tested this in an app? I'm seeing a weird issue in my tests trying to use this. Didn't get back here in time to warn you!

**Comment by kiwiupover** [comment]
I did run it in a dummy app. It was fine there. I have not pushed a new npm version so we are all good.

**Comment by wagenet** [comment]
@kiwiupover If I find any bug in this stuff I'll submit another PR for it. Might have just unearthed something strange in my own app.

**Comment by kiwiupover** [comment]
@wagenet interesting

What are you working on?

**Comment by wagenet** [comment]
Looks like there's an issue with broccoli-asset-rev and ember-auto-import. Trying to see if I can fix the issue in broccoli-asset-rev.

**Comment by wagenet** [comment]
https://github.com/rickharrison/broccoli-asset-rewrite/pull/67

**Pull request merged**
